mapping = {
    'ΠΛΑΤΕΙΑ ΒΙΚΤΩΡΙΑΣ ΑΘΗΝΑ': 'Athens',
    'ΚΟΛΩΝΟΣ': 'Athens',
    'ΣΕΠΟΛΙΑ': 'Athens',
    'ΑΘΗΝΑ ΒΟΤΑΝΙΚΟΣ': 'Athens',
    'ΠΛΑΚΑ ΘΗΣΕΙΟ': 'Athens',
    'ΕΥΑΓΓΕΛΙΣΜΟΣ': 'Athens',
    'ΚΥΠΡΙΑΔΟΥ ΑΘΗΝΑ': 'Athens',
    'ΓΚΥΖΗ': 'Athens',
    'ΕΛΛΗΝΟΡΡΩΣΩΝ': 'Athens',
    'ΜΙΧΑΛΑΚΟΠΟΥΛΟΥ': 'Athens',
    'ΠΕΤΡΑΛΩΝΑ ΚΑΤΩ': 'Athens',
    'ΒΟΤΑΝΙΚΟΣ': 'Athens',

    'ΠΕΡΙΣΤΕΡΙ': 'Peristeri',
    'ΑΙΓΑΛΕΩ ΑΝΑΓΕΝΝΗΣΗ': 'Egaleo',
    'ΑΓΙΑ ΒΑΡΒΑΡΑ': 'Agia Varvara',
    'ΧΑΙΔΑΡΙ': 'Chaidari',
    'ΧΑΙΔΑΡΙ ΔΑΣΟΣ': 'Chaidari',

    'ΝΕΑ ΛΙΟΣΙΑ ΠΑΛΑΤΙΑΝΗ': 'Ilion',
    'ΠΕΤΡΟΥΠΟΛΗ': 'Petroupoli',
    'ΑΓΙΑ ΑΝΑΡΓΥΡΟΙ': 'Agii Anargyri - Kamatero',
    'ΝΕΑ ΙΩΝΙΑ ΙΩΝΙΑ': 'Nea Ionia',
    'ΝΕΟΚΤΙΣΤΑ ΝΕΑΠΟΛΕΩΣ': 'Ilion',

    'ΝΕΑ ΦΙΛΑΔΕΛΦΕΙΑ': 'Filadelfeia-Chalkidona',

    'ΜΑΡΟΥΣΙ ΝΕΑ ΦΙΛΟΘΕΗ': 'Marousi',
    'ΜΑΡΟΥΣΙ ΠΑΡΑΔΕΙΣΟΣ': 'Marousi',
    'ΜΑΡΟΥΣΙ ΝΕΑ ΛΕΣΒΟΣ': 'Marousi',
    'ΜΕΛΙΣΣΙΑ': 'Penteli',

    'ΧΑΛΑΝΔΡΙ ΑΓΙΑ ΒΑΡΒΑΡΑ': 'Chalandri',
    'ΧΑΛΑΝΔΡΙ': 'Chalandri',
    'ΠΕΝΤΕΛΗ ΝΕΑ ΠΕΝΤΕΛΗΟΡ': 'Penteli',
    'ΦΙΛΟΘΕΗ': 'Filothei-Psychiko',

    'ΑΓΙΑ ΠΑΡΑΣΚΕΥΗ ΝΕΑ ΖΩΗ': 'Agia Paraskevi',
    'ΑΓΙΑ ΠΑΡΑΣΚΕΥΗ ΑΓΙΑΝΝΗ': 'Agia Paraskevi',
    'ΑΓΙΑ ΠΑΡΑΣΚΕΥΗ ΠΕΥΚΑΚΙ': 'Agia Paraskevi',

    'ΑΝΘΟΥΣΑ': None,
    'ΠΑΛΛΗΝΗ': None,
    'ΓΛΥΚΑ ΝΕΡΑ': None,

    'ΝΕΑ ΨΥΧΙΚΟ': 'Filothei-Psychiko',
    'ΨΥΧΙΚΟ ΑΓΙΑ ΔΗΜΗΤΡΙΟΣ': 'Filothei-Psychiko',
    'ΧΟΛΑΡΓΟΣ ΠΛΑΤΕΙΑ ΕΘ ΝΕΑ ΑΝΤΙ': 'Papagou-Cholargos',
    'ΠΑΠΑΓΟΥ': 'Papagou-Cholargos',

    'ΖΩΓΡΑΦΟΥ ΑΝΩ ΙΛΙΣΙΑ': 'Zografos',
    'ΖΩΓΡΑΦΟΥ ΓΟΥΔΙ': 'Zografos',
    'ΠΑΝΕΠΙΣΤΗΜΙΟΥΠΟΛΗ': 'Zografos',
    'ΚΑΙΣΑΡΙΑΝΗ ΑΝΩ ΚΑΙΣΑΡΙΑΝΗ': 'Kessariani',

    'ΒΥΡΩΝΑΣ': 'Vyronas',
    'ΒΥΡΩΝ ΖΩΟΔΟΧΟΣ ΠΗΓΗ': 'Vyronas',

    'ΗΛΙΟΥΠΟΛΗ ΚΑΤΩ ΗΛΙΟΥΠΟΛΗ': 'Ilioupoli',
    'ΗΛΙΟΥΠΟΛΗ ΑΣΤΥΝΟΜΙΚΑ': 'Ilioupoli',
    'ΗΛΙΟΥΠΟΛΗ ΑΝΩ ΗΛΙΟΥΠΟΛΗ': 'Ilioupoli',

    'ΑΡΓΥΡΟΥΠΟΛΗ': 'Elliniko-Argyroupoli',
    'ΒΟΥΛΙΑΓΜΕΝΗ  ΜΙΚΡΟ ΚΑΒΟΥΡΙ': None,
    'ΒΑΡΗ': None,
    'ΒΟΥΛΑ ΑΝΩ ΒΟΥΛΑ': None,
    'ΓΛΥΦΑΔΑ': 'Glyfada',
    'ΕΛΛΗΝΙΚΟ ΑΓΙΑ ΠΑΡΑΣΚΕΥ': 'Elliniko-Argyroupoli',

    'ΝΕΑ ΣΜΥΡΝΗ': 'Nea Smyrni',
    'ΝΕΑ ΣΜΥΡΝΗ ΑΝΩ ΝΕΑ ΣΜΥΡΝ': 'Nea Smyrni',

    'ΑΓΙΑ ΔΗΜΗΤΡΙΟΣ': 'Agios Dimitrios',
    'ΑΛΙΜΟΣ ΚΑΛΑΜΑΚΙ': 'Alimos',
    'ΑΛΙΜΟΣ ΕΚΤΕΛΩΝΙΣΤΩΝ': 'Alimos',
    'Π.ΦΑΛΗΡΟ': 'Palaio Faliro',
    'ΚΑΛΛΙΘΕΑ ΠΛΑΤΕΙΑ ΚΑΛΛΙΘΕΑ': 'Kallithea',
    'ΤΑΥΡΟΣ': 'Moschato-Tavros',
    'ΑΓΙΑ Ι.ΡΕΝΤΗΣ': 'Nikaia-Agios Ioannis Rentis',
    'ΜΟΣΧΑΤΟ': 'Moschato-Tavros',

    'ΝΙΚΑΙΑ ΑΣΠΡΑ ΧΩΜΑΤΑ': 'Nikaia-Agios Ioannis Rentis',

    'ΠΕΙΡΑΙΑΣ ΚΑΣΤΕΛΛΑ': 'Piraeus',
    'ΠΕΙΡΑΙΑΣ ΠΛΑΤΕΙΑ ΑΛΕΞΑΝΔΡ': 'Piraeus',
    'ΠΕΙΡΑΙΑΣ ΑΓΙΑ ΝΙΚΟΛΑΟΣ': 'Piraeus',
    'ΠΕΙΡΑΙΑΣ ΧΑΤΖΗΚΥΡΙΑΚ': 'Piraeus',
    'ΠΕΙΡΑΙΑΣ ΑΠΟΛΛΩΝΟΣ': 'Piraeus',

    'ΚΕΡΑΤΣΙΝΙ ΑΜΦΙΑΛΗ': 'Keratsini-Drapetsona',

    'ΠΑΙΑΝΙΑ': None,
    'ΚΟΡΩΠΙ KΑΡΕΛΛΑΣ': None
}
municipality_population = {
    "Agia Paraskevi": 62147,
    "Agia Varvara": 26758,
    "Agii Anargyri - Kamatero": 61461,
    "Agios Dimitrios": 71664,
    "Egaleo": 65831,
    "Alimos": 43174,
    "Marousi": 71830,
    "Athens": 643449,
    "Chaidari": 47049,
    "Chalandri": 77100,
    "Dafni-Ymittos": 33886,
    "Elliniko-Argyroupoli": 50027,
    "Filadelfeia-Chalkidona": 34961,
    "Filothei-Psychiko": 27635,
    "Galatsi": 57910,
    "Glyfada": 89600,
    "Ilion": 84004,
    "Ilioupoli": 76732,
    "Irakleio": 50494,
    "Kessariani": 26268,
    "Kallithea": 97617,
    "Keratsini-Drapetsona": 89537,
    "Kifisia": 72880,
    "Korydallos": 61247,
    "Lykovrysi-Pefki": 30999,
    "Metamorfosi": 30172,
    "Moschato-Tavros": 39658,
    "Nea Ionia": 64613,
    "Nea Smyrni": 72851,
    "Nikaia-Agios Ioannis Rentis": 103490,
    "Palaio Faliro": 64862,
    "Papagou-Cholargos": 45264,
    "Piraeus": 168152,
    "Penteli": 35613,
    "Perama": 25626,
    "Peristeri": 133632,
    "Petroupoli": 60146,
    "Vrilissia": 32414,
    "Vyronas": 59135,
    "Zografos": 69872
}